# Generated by Django 3.1 on 2020-08-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
