# Generated by Django 3.1 on 2020-08-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200831_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='youtube_link_1',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='album',
            name='youtube_link_2',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='album',
            name='youtube_link_3',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='album',
            name='youtube_link_4',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='album',
            name='youtube_link_5',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
