# Generated by Django 3.1 on 2020-09-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200831_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='album_arts/')),
                ('release_year', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('artist', models.CharField(max_length=100)),
                ('youtube_link_1', models.URLField(blank=True, max_length=300)),
                ('youtube_link_2', models.URLField(blank=True, max_length=300)),
                ('youtube_link_3', models.URLField(blank=True, max_length=300)),
                ('youtube_link_4', models.URLField(blank=True, max_length=300)),
                ('youtube_link_5', models.URLField(blank=True, max_length=300)),
                ('is_album', models.BooleanField(default=True)),
                ('is_sound_track', models.BooleanField(default=False)),
                ('is_community_work', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
